spring:
  datasource:
    url: jdbc:h2:file:./data/mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # or create, create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console